### ISSUE TITLE
Double acute accent looks slightly off-center on "o" and "u"

### ISSUE THREAD

**Issue by ghost** [aliftype/xits#92]
**Describe the bug**
When typing the "o" and "u" letters with a double acute accent, the diacritic looks slightly off-center; this happens for every font shape and series, uppercase and lowercase.

**To Reproduce**
Type "o" or "u" with a double acute accent.

**Expected behavior**
The space between the two accents should be centered at the top of the glyph, not the second accent.
**Screenshots**
Here I show how XITS compared to TeX Gyre Termes and Latin Modern.
![doubleacute](https://user-images.githubusercontent.com/62188027/76978003-6f057300-6936-11ea-8857-acd2f62adb1b.PNG)

**Additional context**
This happens on TeXLive 2019 with LuaTeX 1.10 and XITS 1.301.

**Comment by dbenjaminmiller** [comment]
![erdős](https://user-images.githubusercontent.com/43855846/79193409-93028a00-7df8-11ea-9767-f55094f1ce58.png)
You'll see this is different from how Times does things. Compare the left (Linotype Times, I believe) with XITS/STEP on the right. I might change this in STEP (my fork — https://github.com/dbenjaminmiller/step on here) if there is a real demand. I am Hungarian after all!
![image](https://user-images.githubusercontent.com/43855846/79193557-d9f07f80-7df8-11ea-8b21-357fdfe27c9e.png)
Cf. also Nimbus Roman, shown here.

**Comment by manuelboni** [comment]
@dbenjaminmiller Thanks for sharing your thoughts on the matter. If the accent placement is just a stylistic choice and not an issue, then I am okay with leaving things as they are.

**Comment by khaledhosny** [comment]
Accent placement and shape often varies from language to another. I don’t have the capacity to research this right now, so unless there is a strong indication we are doing something that is completely wrong, I’d rather keep things the way they are.
